### PR TITLE
Feature PdfPlumberParser along with componnent file and test file.  #496

### PR DESCRIPTION
**Pull request by Rexon-Pambujya**
**Issue No:** - #496 

## Feature Description

This feature introduces the PDFPlumberParser class, which utilizes the `PDF plumber` library to extract text from PDF documents. Implementing this parser enables efficient and accurate parsing of PDF files to retrieve text content, handling both file paths and byte streams as input.

### Files Added:

- [x] `pkgs/community/swarmauri_community/parsers/concrete/PDFPlumberParser.py` This file contains the core implementation of the PDFPlumberParser class. The parser reads text content from PDF files page by page, storing each page's text as a Document instance with metadata, including the page number. It supports file path and byte input, making it flexible for different use cases. Exception handling is included to manage cases where files may be missing or unreadable.

- [x] `pkgs/community/tests/unit/parsers/PDFPlumberParser_test.py` This test file provides comprehensive unit tests for PDFPlumberParser. It includes cases to verify. Successful extraction of text from a PDF file. Parsing when input is provided as bytes. Appropriate error handling for unsupported source types. Robustness when encountering non-existent files. Each test validates the extracted text and metadata, ensuring the parser performs reliably across different inputs.

> I kindly request the maintainers to review this code and provide feedback.

### CODE REVIEW

**Comment by cobycloud** [comment]
please raise a PR for each individual component. to raise multiple PRs, create separate feature branches on your fork, fetch the upstream to sync your forked branch to a given point

**Review by cobycloud — CHANGES_REQUESTED** [review]
split into two PRs so the team can tackle these independently

**Comment by Rexon-Pambujya** [comment]
Have made the necessary changes to the branch. Apologies for the mistake!

**Comment by cobycloud** [comment]
thank you kindly, we'll review shortly

**Pull request merged**
